name       : id3lib
version    : 3.8.3
release    : 1
source     :
    - http://skylink.dl.sourceforge.net/project/id3lib/id3lib/3.8.3/id3lib-3.8.3.tar.gz : 2749cc3c0cd7280b299518b1ddf5a5bcfe2d1100614519b68702230e26c7d079
license    : LGPL-2.0
summary    : id3lib is a software library for reading, writing, and manipulating ID3v2 tags.
description: |
    id3lib is a software library for reading, writing, and manipulating ID3v2 tags.
setup      : |
    for patchfile in $pkgfiles/*.patch; do
        echo "Patching with $patchfile"
        %patch -p1 < $patchfile
    done
    %patch -p1 < $pkgfiles/security/CVE-2007-4460.patch
    libtoolize -fc
    aclocal
    autoconf
    automake --add-missing --copy
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
